remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Lecture Notes for CHEM 576 Computational Biology"
description: "A comprehensive collection of course materials and lecture notes"
show_downloads: false