remote_theme: sighingnow/jekyll-gitbook
title: "Lecture Notes for CHEM 576 Computational Biology"
description: "A comprehensive collection of course materials and lecture notes"
favicon_path: /assets/images/yeast_geometry.ico
show_downloads: false
toc:
    enabled: true
    h_min: 1
    h_max: 3
# url settings
url:              'https://forxhunter.github.io'
baseurl:          '/CHEM576'
# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md
# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow


# collections
exclude:
  - _drafts
  - _posts/2025-1-1-index.md
  # - _posts/2025-1-2-week2.md
  # - _posts/2025-1-2-week3.md
  # - _posts/2025-1-2-week4.md
  # - _posts/2025-1-2-week5.md
  # - _posts/2025-1-2-week6.md
  - _posts/2025-1-2-week7.md
  - _posts/2025-1-2-week8.md
  - _posts/2025-1-2-week9.md
  - _posts/2025-1-3-week10.md
collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
  
ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

plugins:
  - jekyll-feed
  - jemoji