remote_theme: sighingnow/jekyll-gitbook
syntax_highlighter_style: colorful
toc:
    enabled: true
    h_min: 1
    h_max: 3
title: "Lecture Notes for CHEM 576 Computational Biology"
description: "A comprehensive collection of course materials and lecture notes"
favicon: "./assets/images/yeast_geometry.ico"
show_downloads: false
