remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-toc # Adds Table of Contents support
title: "Lecture Notes for CHEM 576 Computational Biology"
description: "A comprehensive collection of course materials and lecture notes"
favicon: /assets/images/yeast_geometry.ico
show_downloads: false